/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eksos.views;

import com.eksos.EksosMenu;
import com.eksos.controllers.FactoryController;
import com.eksos.models.FactoryModel;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class FactoryView extends javax.swing.JFrame {
    
    FactoryController controller = new FactoryController();

    /**
     * Creates new form FactoryView
     */
    public FactoryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jButtonPendingOrders = new javax.swing.JButton();
        jButtonnewOrder = new javax.swing.JButton();
        jButtonhome = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelPendingOrders = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelNewOrder = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRawMaterial = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonSendOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPendingOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/task-square.png"))); // NOI18N
        jButtonPendingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPendingOrdersActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonPendingOrders);

        jButtonnewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box-add.png"))); // NOI18N
        jButtonnewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnewOrderActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonnewOrder);

        jButtonhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-2.png"))); // NOI18N
        jButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhomeActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonhome);

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 800));

        jPanelPendingOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Descripción", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelPendingOrders.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 920, 710));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setText("Confirmar ordenes recibidas");
        jPanelPendingOrders.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 40));

        jLayeredPane1.add(jPanelPendingOrders);
        jPanelPendingOrders.setBounds(0, 0, 1120, 800);

        jPanelNewOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Cantidad de materia prima");
        jPanelNewOrder.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Materia Prima");
        jPanelNewOrder.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanelNewOrder.add(jTextFieldRawMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 220, -1));
        jPanelNewOrder.add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 220, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("Descripción");
        jPanelNewOrder.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescription);

        jPanelNewOrder.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jButtonSendOrder.setText("Enviar Orden al Almacén");
        jButtonSendOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendOrderActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonSendOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLayeredPane1.add(jPanelNewOrder);
        jPanelNewOrder.setBounds(0, 0, 1120, 800);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1130, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhomeActionPerformed
        dispose();
        EksosMenu menu = new EksosMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonhomeActionPerformed

    private void jButtonnewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnewOrderActionPerformed
        jPanelNewOrder.setVisible(true);
        jPanelPendingOrders.setVisible(false);
    }//GEN-LAST:event_jButtonnewOrderActionPerformed

    private void jButtonPendingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPendingOrdersActionPerformed
        jPanelPendingOrders.setVisible(true);
        jPanelNewOrder.setVisible(false);
        jTable1.setModel(controller.getOrders());
    }//GEN-LAST:event_jButtonPendingOrdersActionPerformed

    private void jButtonSendOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendOrderActionPerformed
        if (jTextAreaDescription != null && jTextFieldAmount != null && jTextFieldRawMaterial != null) {
            String material = jTextFieldRawMaterial.getText();
            String amout = jTextFieldAmount.getText();
            String description = jTextAreaDescription.getText();
            FactoryModel model = new FactoryModel();
            model.setProduct_name(material);
            model.setAmount(amout);
            model.setDescription(description);
            try {
                if(controller.AddOrder(model));
                JOptionPane.showMessageDialog(null, "Oreden enviada a Alamacen");
                jTextFieldRawMaterial.setText("");
                jTextFieldAmount.setText("");
                jTextAreaDescription.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No debe tener campos vacíos");
        }
        
        
    }//GEN-LAST:event_jButtonSendOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactoryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPendingOrders;
    private javax.swing.JButton jButtonSendOrder;
    private javax.swing.JButton jButtonhome;
    private javax.swing.JButton jButtonnewOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelNewOrder;
    private javax.swing.JPanel jPanelPendingOrders;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldRawMaterial;
    // End of variables declaration//GEN-END:variables
    private void setUIProperties() {
        this.getContentPane().setBackground(Color.WHITE);
        UIManager.put("ToolTip.background", new Color(0xF8FAFF));
        UIManager.put("ToolTip.foreground", new Color(0x56595F));
        jButtonhome.setToolTipText("Regresar al menú");
        jButtonnewOrder.setToolTipText("Nueva orden");
        jButtonPendingOrders.setToolTipText("Ordenes Pendientes");
        UIManager.put("ToolTip.font", new Font("Arial", Font.PLAIN, 14));
        jPanelNewOrder.setBackground(Color.WHITE);
        jPanelPendingOrders.setBackground(Color.WHITE);
        jPanelNewOrder.setVisible(false);
        jPanelPendingOrders.setVisible(false);
    }
}
