/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eksos.views;

import com.eksos.EksosMenu;
import com.eksos.controllers.OrderController;
import static com.eksos.controllers.OrderController.convertTime;
import com.eksos.controllers.SuppliersController;
import com.eksos.models.Order;
import com.eksos.models.Supplier;
import com.eksos.models.SupplierProduct;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allec
 */
public class SuppliersView extends javax.swing.JFrame {

    private SuppliersController controller = new SuppliersController();
    private OrderController orderController = new OrderController();
    private List<SupplierProduct> mpProducts = new ArrayList<>();

    /**
     * Creates new form Proveedores
     */
    public SuppliersView() {
        initComponents();
        setUIProperties();
        initalComponentsState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jButtonNewSupplier = new javax.swing.JButton();
        jButtonNewOrder = new javax.swing.JButton();
        jButtonOrders = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jLayeredPane = new javax.swing.JLayeredPane();
        jPanelSupplier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSupplier = new javax.swing.JTextField();
        jTextFieldAddres = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jButtonSaveSupplier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonNewProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDimensional = new javax.swing.JLabel();
        jTextFieldDimensional = new javax.swing.JTextField();
        jLabelPrice = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonStoreProduct = new javax.swing.JButton();
        jPanelNewOrder = new javax.swing.JPanel();
        jComboBoxMP = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxSupplier = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCant = new javax.swing.JTextField();
        jButtonCancelOrder = new javax.swing.JButton();
        jButtonSendOrder = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelOrderPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelMPPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabelMPDimensional = new javax.swing.JLabel();
        jPanelOrders = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");
        setBackground(new java.awt.Color(204, 51, 255));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLeft.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 20));

        jButtonNewSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-add.png"))); // NOI18N
        jButtonNewSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewSupplier.setMaximumSize(new java.awt.Dimension(48, 48));
        jButtonNewSupplier.setMinimumSize(new java.awt.Dimension(48, 48));
        jButtonNewSupplier.setPreferredSize(new java.awt.Dimension(48, 48));
        jButtonNewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSupplierActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonNewSupplier);

        jButtonNewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/box-add.png"))); // NOI18N
        jButtonNewOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNewOrder.setDisabledIcon(null);
        jButtonNewOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewOrder.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonNewOrder.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonNewOrder.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonNewOrder);

        jButtonOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/myorders.png"))); // NOI18N
        jButtonOrders.setDisabledIcon(null);
        jButtonOrders.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonOrders.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonOrders.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdersActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonOrders);

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-2.png"))); // NOI18N
        jButtonHome.setDisabledIcon(null);
        jButtonHome.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonHome.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonHome.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanelLeft.add(jButtonHome);

        getContentPane().add(jPanelLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 800));

        jPanelSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Añadir producto");
        jPanelSupplier.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Dirección completa");
        jPanelSupplier.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 32));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Número de contacto");
        jPanelSupplier.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 32));

        jTextFieldSupplier.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 40));

        jTextFieldAddres.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldAddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 400, 40));

        jTextFieldTel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, 40));

        jButtonSaveSupplier.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButtonSaveSupplier.setText("Guardar");
        jButtonSaveSupplier.setBorderPainted(false);
        jButtonSaveSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveSupplier.setIconTextGap(16);
        jButtonSaveSupplier.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jButtonSaveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSupplierActionPerformed(evt);
            }
        });
        jPanelSupplier.add(jButtonSaveSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 140, 48));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("Correo electrónico");
        jPanelSupplier.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 32));

        jTextFieldEmail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 400, 40));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel5.setText("Nuevo proveedor");
        jPanelSupplier.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelSupplier.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 48, 48));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Nombre del proveedor");
        jPanelSupplier.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 32));

        jButtonNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jButtonNewProduct.setBorderPainted(false);
        jButtonNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProductActionPerformed(evt);
            }
        });
        jPanelSupplier.add(jButtonNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 40, 40));

        jTableProducts.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTableProducts.setForeground(new java.awt.Color(0, 0, 0));
        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Tipo de medida", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableProducts.setShowGrid(false);
        jTableProducts.setShowHorizontalLines(true);
        jTableProducts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProducts);
        if (jTableProducts.getColumnModel().getColumnCount() > 0) {
            jTableProducts.getColumnModel().getColumn(2).setMinWidth(120);
            jTableProducts.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTableProducts.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        jPanelSupplier.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 580, 370));

        jLabelName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelName.setText("Descripción");
        jPanelSupplier.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 200, 32));

        jTextFieldName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 400, 40));

        jLabelDimensional.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelDimensional.setText("Tipo de medida");
        jPanelSupplier.add(jLabelDimensional, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, 32));

        jTextFieldDimensional.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldDimensional, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 400, 40));

        jLabelPrice.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabelPrice.setText("Precio");
        jPanelSupplier.add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 200, 32));

        jTextFieldPrice.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelSupplier.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 400, 40));

        jButtonStoreProduct.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonStoreProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-right.png"))); // NOI18N
        jButtonStoreProduct.setText("Agregar");
        jButtonStoreProduct.setBorderPainted(false);
        jButtonStoreProduct.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonStoreProduct.setIconTextGap(5);
        jButtonStoreProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStoreProductActionPerformed(evt);
            }
        });
        jPanelSupplier.add(jButtonStoreProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, 130, 40));

        jLayeredPane.add(jPanelSupplier);
        jPanelSupplier.setBounds(0, 0, 1120, 800);

        jPanelNewOrder.setFocusCycleRoot(true);
        jPanelNewOrder.setFocusTraversalPolicyProvider(true);
        jPanelNewOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxMP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelNewOrder.add(jComboBoxMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 400, 40));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel11.setText("Nueva orden de MP");
        jPanelNewOrder.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setText("Precio total del pedido");
        jPanelNewOrder.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 32));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setText("Escoger proveedor");
        jPanelNewOrder.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 32));

        jComboBoxSupplier.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jPanelNewOrder.add(jComboBoxSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 40));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel14.setText("Medida");
        jPanelNewOrder.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 200, 32));

        jTextFieldCant.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTextFieldCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCantKeyReleased(evt);
            }
        });
        jPanelNewOrder.add(jTextFieldCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 400, 40));

        jButtonCancelOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jButtonCancelOrder.setBorderPainted(false);
        jButtonCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelOrderActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonCancelOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 48, 48));

        jButtonSendOrder.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButtonSendOrder.setText("Enviar orden");
        jButtonSendOrder.setBorderPainted(false);
        jButtonSendOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSendOrder.setIconTextGap(16);
        jButtonSendOrder.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jButtonSendOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendOrderActionPerformed(evt);
            }
        });
        jPanelNewOrder.add(jButtonSendOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 140, 48));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setText("Cantidad de MP");
        jPanelNewOrder.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 32));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel7.setText("GTQ.");
        jPanelNewOrder.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 70, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel16.setText("Escoger MP (Máximo 1)");
        jPanelNewOrder.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 32));

        jLabelOrderPrice.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jPanelNewOrder.add(jLabelOrderPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 180, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel8.setText("GTQ.");
        jPanelNewOrder.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 40, 40));

        jLabelMPPrice.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jPanelNewOrder.add(jLabelMPPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 140, 40));
        jPanelNewOrder.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 260, 30));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel17.setText("Precio unitario");
        jPanelNewOrder.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 32));

        jLabelMPDimensional.setFont(new java.awt.Font("SansSerif", 2, 16)); // NOI18N
        jPanelNewOrder.add(jLabelMPDimensional, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 140, 40));

        jLayeredPane.add(jPanelNewOrder);
        jPanelNewOrder.setBounds(0, 0, 1120, 800);

        jPanelOrders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableOrders.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Proveedor", "Fecha pedido", "Fecha de llegada", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableOrders);
        if (jTableOrders.getColumnModel().getColumnCount() > 0) {
            jTableOrders.getColumnModel().getColumn(0).setMinWidth(80);
            jTableOrders.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableOrders.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanelOrders.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1040, 680));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel18.setText("Ordenes recientes");
        jPanelOrders.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh-circle.png"))); // NOI18N
        jButtonRefresh.setBorderPainted(false);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanelOrders.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 48, 48));

        jLayeredPane.add(jPanelOrders);
        jPanelOrders.setBounds(0, 0, 1120, 800);

        getContentPane().add(jLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1120, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSupplierActionPerformed
        initalComponentsState();
        jPanelSupplier.setVisible(true);
        jPanelNewOrder.setVisible(false);
        jPanelOrders.setVisible(false);
    }//GEN-LAST:event_jButtonNewSupplierActionPerformed

    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
        initalComponentsState();
        jPanelSupplier.setVisible(false);
        jPanelNewOrder.setVisible(true);
        jPanelOrders.setVisible(false);
        List<String> suppliers = controller.getAllSuppliersNames();
        for (String supplier : suppliers) {
            jComboBoxSupplier.addItem(supplier);
        }
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        dispose();
        EksosMenu menu = new EksosMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonSaveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSupplierActionPerformed
        String name = jTextFieldSupplier.getText();
        String address = jTextFieldAddres.getText();
        String tel = jTextFieldTel.getText();
        String email = jTextFieldEmail.getText();
        Supplier supplier = new Supplier();
        supplier.setSupplierName(name);
        supplier.setAddress(address);
        supplier.setTel(tel);
        supplier.setEmail(email);

        DefaultTableModel tableModel = (DefaultTableModel) jTableProducts.getModel();
        List<SupplierProduct> supplierProducts = new ArrayList<>();
        for (int row = 0; row < tableModel.getRowCount(); row++) {
            SupplierProduct supplierProduct = new SupplierProduct();
            for (int column = 0; column < tableModel.getColumnCount(); column++) {
                if (column == 0) {
                    supplierProduct.setName(tableModel.getValueAt(row, column).toString());
                } else if (column == 1) {
                    supplierProduct.setDimensional(tableModel.getValueAt(row, column).toString());
                } else if (column == 2) {
                    supplierProduct.setPrice(Double.valueOf(tableModel.getValueAt(row, column).toString()));
                }
            }
            controller.creatNewSupplierProduct(supplierProduct);
            supplierProducts.add(supplierProduct);
        }
        if (!supplierProducts.isEmpty()) {
            supplier.setSupplierProducts(supplierProducts);
        }

        if (controller.createNewSupplier(supplier)) {
            System.out.println("Si se ingreso");
        } else {
            System.out.println("No se ingreso");
        }
        initalComponentsState();
    }//GEN-LAST:event_jButtonSaveSupplierActionPerformed

    private void jButtonNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProductActionPerformed
        jLabelName.setVisible(true);
        jTextFieldName.setVisible(true);
        jLabelDimensional.setVisible(true);
        jTextFieldDimensional.setVisible(true);
        jLabelPrice.setVisible(true);
        jTextFieldPrice.setVisible(true);
        jScrollPane1.setVisible(true);
        jButtonStoreProduct.setVisible(true);
    }//GEN-LAST:event_jButtonNewProductActionPerformed

    private void jButtonStoreProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStoreProductActionPerformed
        String data[] = {jTextFieldName.getText(),
            jTextFieldDimensional.getText(), jTextFieldPrice.getText()};
        DefaultTableModel tableModel = (DefaultTableModel) jTableProducts.getModel();
        tableModel.addRow(data);
        jTextFieldName.setText("");
        jTextFieldDimensional.setText("");
        jTextFieldPrice.setText("");
    }//GEN-LAST:event_jButtonStoreProductActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        initalComponentsState();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelOrderActionPerformed
        initalComponentsState();
    }//GEN-LAST:event_jButtonCancelOrderActionPerformed

    private void jButtonSendOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendOrderActionPerformed
        String supplierName = jComboBoxSupplier.getSelectedItem().toString();
        String mpName = jComboBoxMP.getSelectedItem().toString();
        String amount = jTextFieldCant.getText();
        String totalPrice = jLabelOrderPrice.getText();
        Order newOrder = new Order();
        newOrder.setNumberOfOrder(supplierName.substring(0, 4) + "-01");
        newOrder.setSupplier(controller.getSupplier(supplierName));
        newOrder.setTotalPrice(Double.valueOf(totalPrice));
        newOrder.setAmount(Integer.valueOf(amount));
        newOrder.setStatus(Order.OrderStatus.UNDER_REVIEW);
        newOrder.setMp(controller.getMPbyName(mpName));
        if (orderController.createNewOrder(newOrder)) {
            System.out.println("Si se ingreso");
        } else {
            System.out.println("NO se ingreso");
        }
        initalComponentsState();
    }//GEN-LAST:event_jButtonSendOrderActionPerformed

    private void jTextFieldCantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantKeyReleased
        if (jTextFieldCant.getText().isBlank()) {
            jLabelOrderPrice.setText("");
            jLabelOrderPrice.setText("0.00");
        } else {
            Double totalPrice = Double.valueOf(jLabelMPPrice.getText()) * Double.valueOf(jTextFieldCant.getText());
            jLabelOrderPrice.setText("");
            jLabelOrderPrice.setText(String.valueOf(Math.round(totalPrice * 100.0) / 100.0));
        }
    }//GEN-LAST:event_jTextFieldCantKeyReleased

    private void jButtonOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdersActionPerformed
        initalComponentsState();
        jPanelSupplier.setVisible(false);
        jPanelNewOrder.setVisible(false);
        jPanelOrders.setVisible(true);
        List<Order> orders = orderController.getAllOrders();
        DefaultTableModel tableModel = (DefaultTableModel) jTableOrders.getModel();
        for (Order order : orders) {
            String data[] = new String[5];
            data[0] = order.getNumberOfOrder();
            data[1] = order.getSupplier().getSupplierName();
            data[2] = convertTime(order.getDateOfOrder());
            data[3] = convertTime(order.getDateOfArrival());
            data[4] = order.getStatus().toString();
            tableModel.addRow(data);
        }
    }//GEN-LAST:event_jButtonOrdersActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        initalComponentsState();
        List<Order> orders = orderController.getAllOrders();
        DefaultTableModel tableModel = (DefaultTableModel) jTableOrders.getModel();
        for (Order order : orders) {
            String data[] = new String[5];
            data[0] = order.getNumberOfOrder();
            data[1] = order.getSupplier().getSupplierName();
            data[2] = convertTime(order.getDateOfOrder());
            data[3] = convertTime(order.getDateOfArrival());
            data[4] = order.getStatus().toString();
            tableModel.addRow(data);
        }
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancelOrder;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNewOrder;
    private javax.swing.JButton jButtonNewProduct;
    private javax.swing.JButton jButtonNewSupplier;
    private javax.swing.JButton jButtonOrders;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSaveSupplier;
    private javax.swing.JButton jButtonSendOrder;
    private javax.swing.JButton jButtonStoreProduct;
    private javax.swing.JComboBox<String> jComboBoxMP;
    private javax.swing.JComboBox<String> jComboBoxSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDimensional;
    private javax.swing.JLabel jLabelMPDimensional;
    private javax.swing.JLabel jLabelMPPrice;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelOrderPrice;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelNewOrder;
    private javax.swing.JPanel jPanelOrders;
    private javax.swing.JPanel jPanelSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTextField jTextFieldAddres;
    private javax.swing.JTextField jTextFieldCant;
    private javax.swing.JTextField jTextFieldDimensional;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldSupplier;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables

    private void setUIProperties() {
        this.getContentPane().setBackground(Color.WHITE);
        UIManager.put("ToolTip.background", new Color(0xF8FAFF));
        UIManager.put("ToolTip.foreground", new Color(0x56595F));
        jButtonNewSupplier.setToolTipText("Nuevo proveedor");
        jButtonNewOrder.setToolTipText("Nueva orden");
        jButtonHome.setToolTipText("Regresar al menu");
        UIManager.put("ToolTip.font", new Font("Arial", Font.PLAIN, 14));
        jPanelSupplier.setBackground(Color.WHITE);
        jPanelNewOrder.setBackground(Color.WHITE);
        jPanelOrders.setBackground(Color.WHITE);
        jButtonSaveSupplier.setBackground(new Color(0x0C31A6));
        jButtonSaveSupplier.setForeground(Color.WHITE);
        jButtonSendOrder.setBackground(new Color(0x0C31A6));
        jButtonSendOrder.setForeground(Color.WHITE);
        jPanelSupplier.setVisible(false);
        jPanelNewOrder.setVisible(false);
        jPanelOrders.setVisible(false);
        jTableProducts.getTableHeader().setFont(new Font("SansSerif", Font.PLAIN, 18));
        jTableOrders.getTableHeader().setFont(new Font("SansSerif", Font.PLAIN, 18));
        jLabelOrderPrice.setForeground(new Color(0x00E9A3));
    }

    private void initalComponentsState() {
        jLabelName.setVisible(false);
        jTextFieldName.setVisible(false);
        jLabelDimensional.setVisible(false);
        jTextFieldDimensional.setVisible(false);
        jLabelPrice.setVisible(false);
        jTextFieldPrice.setVisible(false);
        jScrollPane1.setVisible(false);
        jButtonStoreProduct.setVisible(false);
        jTextFieldSupplier.setText("");
        jTextFieldAddres.setText("");
        jTextFieldTel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldName.setText("");
        jTextFieldDimensional.setText("");
        jTextFieldPrice.setText("");
        jLabelMPPrice.setText("");
        jLabelOrderPrice.setText("");
        jTextFieldCant.setText("");
        DefaultTableModel tableModelProducts = (DefaultTableModel) jTableProducts.getModel();
        tableModelProducts.setRowCount(0);
        DefaultTableModel tableModelOrder = (DefaultTableModel) jTableOrders.getModel();
        tableModelOrder.setRowCount(0);
        jComboBoxMP.removeAllItems();
        jComboBoxSupplier.removeAllItems();
        jComboBoxSupplier.addItemListener(new SupplierChangeListener());
        jComboBoxMP.addItemListener(new MPChangeListener());
    }

    class SupplierChangeListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                jComboBoxMP.removeAllItems();
                Object item = event.getItem();
                List<String> products = controller.getSupplierProducts(item.toString());
//                mpProducts = products;
                for (String product : products) {
                    jComboBoxMP.addItem(product);
                }
            }
        }
    }

    class MPChangeListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                jLabelMPPrice.setText("");
                Object item = event.getItem();
                SupplierProduct mpProduct = controller.getMPbyName(item.toString());
                String price = String.valueOf(mpProduct.getPrice());
                jLabelMPPrice.setText(price);
                String dimensional = String.valueOf(mpProduct.getDimensional());
                jLabelMPDimensional.setText(dimensional);
            }
        }
    }
}
